### PR TITLE
Implement group- and null-safe functions.

### PR DESCRIPTION
**Pull request by mgold**
Although you don't see it in common usage, D3 selections may contain null elements, and may contain multiple groups within the outer array. You can get null elements in nested selections:

`d3.selectAll(".foo").select(".bar")`

If not every foo has a bar, those that don't will have null elements. If some but not all elements exit, the exit selection will contain `undefined` in order to preserve index. D3 [skips](https://github.com/mbostock/d3/blob/master/src/selection/each.js#L12) falsey values for you.

Second, selections can be [nested](http://bost.ocks.org/mike/nest/). You cannot, in general, expect the outer array to have only one element. I have replaced all instances of `selection[0]`. Let's go through them:

**eq** would only find elements in the first group. I added an optional second argument to find elements in later groups. The well-known index `i` is the index within the group; the little-known third argument `j` is the index of the group. Also, it did not skip null values - the first item might not be at index 0...

...which is problematic for **first and last**. I could have implemented these on top of `selection.each` but instead I copied from the implementation to short-circuit as soon as a non-null value was found. We also continue searching groups after the first, and for last, start at the end.

**size**: D3 already provides a [size](https://github.com/mbostock/d3/wiki/Selections#size) operator that accounts for groups and nulls. Currently, importing the extension _overwrites it with incorrect behavior_. There's not much to do but delete it entirely.

I also changed a reference from `[0]` to `size()` in **appendTo**.

---

`npm install; npm test` fails for me with the error below, even on a clean master. I am happy to update tests if you help me figure out what's wrong. (OS X Yosemite, npm 2.0.0)

```
> d3-extended@1.0.0 test /Users/me/Desktop/d3-extended
> browserify test/*-test.js | node_modules/.bin/tape-run

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

---

I know that seems rough, but I'm contributing because I think there are some useful functions in here, and that a healthy, quality open source community serves everyone.

### CODE REVIEW

**Comment by moklick** [comment]
Hey. Thanks for your help! Very good points ..

Unfortunately we can not merge your PR, because we are not working on the d3-extended.js file but on the files that are in the src folder. Could you create a new PR where you change the files in the src folder?

I will delete the size function. Thanks for the hint! 
We will also check what is wrong with the tests!

**Comment by mgold** [comment]
I made the changes to the files in the src folder, and then ran `gulp` to compile the d3-extended.js file.

**Comment by chrtze** [comment]
Ok. we will look into it and merge ASAP!

**Comment by moklick** [comment]
Thanks @mgold

**Comment by mgold** [comment]
No problem. I'm glad to see 3rd party libraries that don't try to hide D3's advanced features.

**Comment by chrtze** [comment]
Hi @mgold ! I had the same ENOENT error you have mentioned before. After running ```npm install -g phantomjs``` it worked. Can you try and confirm? Greetings, Christopher

**Comment by mgold** [comment]
Confirmed. Better late than never to add it to the README?

**Pull request merged**
